# @format

name: Paris sportifs
on:
    push:
        branches: ["master"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            - name: Test python Code 
              run: |
                  pip install pytest requests 
                  pip install -r src/data_generation/requirements.txt
                  python3 -m pytest src/data_generation/test_data_loader.py
                  docker-compose up -d
                  python3 -m pytest tests/test_api.py
                  python3 -m pytest tests/test_model.py


    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOSTNAME  }}
                  username: ubuntu
                  key: ${{ secrets.AWS_PRIVATE_KEY  }}
                  port: 22

                  script: |
                      pwd