# @format

name: Paris sportifs
on:
    push:
        branches: ["master"]

jobs:
    test_data_loader:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            - name: Test data loader 
              run: |
                  pip install pytest requests joblib scikit-learn
                  pip install -r src/data_generation/requirements.txt
                  python3 -m pytest src/data_generation/test_data_loader.py

    test_api:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            - name: Test api health after docker compose 
              run: |
                  pip install pytest requests joblib scikit-learn
                  pip install -r src/data_generation/requirements.txt
                  docker-compose up -d
                  python3 -m pytest tests/test_api.py
                  

    test_model:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            - name: Test api health after docker compose 
              run: |
                  pip install pytest requests joblib scikit-learn
                  pip install -r src/data_generation/requirements.txt              
                  python3 -m pytest tests/test_model.py


    build:
        runs-on: ubuntu-latest
        needs: [test_data_loader, test_api, test_model]
        if: success()
        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOSTNAME  }}
                  username: ubuntu
                  key: ${{ secrets.AWS_PRIVATE_KEY  }}
                  port: 22

                  script: |
                      pwd
                      mkdir -p /home/ubuntu/build_atp
                      cd /home/ubuntu/build_atp

                      git clone -b prod https://github.com/parisds2024/atp_mlops.git
                      cd build_atp
                      
                      sudo docker-compose down

                      sleep 5
                      docker-compose up -d --build